baseURL = "http://www.caloni.com.br/"
languageCode = "pt-br"
title = "Blogue do Caloni"
copyright = ""
disableKinds = [ "sitemap" ]
theme = "blog"

[outputs]
  home = ["HTML", "RSS"]

[outputFormats]

[outputFormats.CSV]
    isPlainText = true
    mediaType = "text/csv"

[permalinks]
    posts = "/:filename/"

[params]
    contentGit = "https://github.com/Caloni/blog"
    namespace = "caloni"
    author = "Wanderley Caloni"
    showFilterAfter = 1
    comments = "https://t.me/bloguedocalonidiscuss"

[params.home]
    postsCount = 5
    tagPostsCount = 15
    tags = [ "home" ]
    intro = "Olá! Este costumava ser um blogue técnico, mas ao longo dos anos outros interesses acabaram ocupando minha rotina e agora vários assuntos se mesclaram. Fique à vontade para começar sua navegação pelas categorias com temas mais fixos, as tags e seus temas mais vagos e, por fim, todos os posts disponíveis (clique com cuidado, são milhares). Antes que eu me esqueça: seja muito bem-vindo =)."

[params.external]

[params.external.cinemaqui]
    tag = "cinemaqui"
    name = "Cinemaqui"
    searchLink = "http://www.cinemaqui.com.br/?s="
    summaryOnly = true
    expire = -12

[params.external.ccppbr]
    tag = "ccppbr"
    name = "C/C++ Brasil"
    link = "http://ccppbrasil.github.io"

[params.external.chesstempo]
    tag = "chesstempo"
    name = "Chess Tempo"
    link = "http://chesstempo.com/"

[markup.goldmark]

[markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = false

[markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"

[markup.goldmark.renderer]
    hardWraps = false
    unsafe = false
    xhtml = false
