baseURL = "http://www.cinetenisverde.com.br/"
languageCode = "en-us"
title = "Cine TÃªnis Verde"
theme = "capsule"
disqusShortname = "cinetenisverde"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "?"

[taxonomies]
     category = "categories"

[permalinks]
    post = "/:filename/"
    note = "/:filename/"

[[menu.main]]
    name = "search"
    url = "/post"
    weight = 1
[[menu.main]]
    name = "google"
    url = "https://www.google.com/search?as_sitesearch=cinetenisverde.com.br"
    weight = 2
[[menu.main]]
    name = "twitter"
    url = "https://twitter.com/cinetenisverde"
    weight = 3
[[menu.main]]
    name = "link"
    url = "/leituras"
    weight = 4
[[menu.main]]
    name = "rss"
    url = "/index.xml"
    weight = 5

[params]
    description = "A website built through Hugo and blogdown."
    googleAnalytics = "UA-50557403-1"
    yandexVerification = "48a8210fc043c5e8"
    repo = "https://github.com/Caloni/cinetenisverde"
