baseURL = "/"
languageCode = "en-us"
title = "Blogue do Caloni"
theme = "hugo-xmin"
googleAnalytics = "UA-50557403-2"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "?"

[permalinks]
    post = "/:filename/"
    note = "/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 5

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Wanderley Caloni](/sobre) | [Github](https://github.com/caloni) | [Twitter](https://twitter.com/caloni) | [Links](/links) | [Leituras](/leituras)"
    googleSearch = "005399618489749432245:zflfst4-oeq"
